// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8eP5z9Z1HlcsyQJKU0Htm8MzIIcqrCxQ',
    appId: '1:209912940395:web:806ae80fb04b79bc68ae2e',
    messagingSenderId: '209912940395',
    projectId: 'wisuda-7467d',
    authDomain: 'wisuda-7467d.firebaseapp.com',
    storageBucket: 'wisuda-7467d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLI-jKeYvJABj-1ZdO0sX7URaS85Tie0k',
    appId: '1:209912940395:android:064aae90919565cc68ae2e',
    messagingSenderId: '209912940395',
    projectId: 'wisuda-7467d',
    storageBucket: 'wisuda-7467d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHRIfEBVtaTr4-4zaHPR_L9mJx66MHlE',
    appId: '1:209912940395:ios:6b1b7c341f31901168ae2e',
    messagingSenderId: '209912940395',
    projectId: 'wisuda-7467d',
    storageBucket: 'wisuda-7467d.appspot.com',
    iosClientId: '209912940395-pir2ojq6u71asj10pm9hcluf07gfoqit.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHRIfEBVtaTr4-4zaHPR_L9mJx66MHlE',
    appId: '1:209912940395:ios:6b1b7c341f31901168ae2e',
    messagingSenderId: '209912940395',
    projectId: 'wisuda-7467d',
    storageBucket: 'wisuda-7467d.appspot.com',
    iosClientId: '209912940395-pir2ojq6u71asj10pm9hcluf07gfoqit.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
